jobs:

# jobs for the dv pipeline from CI thru TEST environment


# manifest gen for VISUALIZER
  - name: dv-man1
    type: manifest
    steps:
      - IN: dv-img1
      - IN: dv-img-opts1
      - TASK: managed

#/ manifest gen for VISUALIZER

# TEST deployment for VISUALIZER to Amazon ECS
  - name: dv-test-ecs1
    type: deploy
    steps:
      - IN: dv-man1
#      - IN: dv-params
      - IN: env-test-ecs1
      - TASK: managed

# / TEST deployment for VISUALIZER to Amazon ECS
